# we only CI the master, release branches, tags and PRs
#if: tag IS present OR type = pull_request OR ((branch = master OR branch =~ release-*) AND type = push)

language: python
# cache package wheels (1 cache per python version)
cache: pip
# newer python versions are available only on xenial (while some older only on trusty) Ubuntu distribution
dist: xenial
sudo: required

env:
  TOXENV=py
  EXTRA_ARGS="-n 12"

jobs:
  include:
  - name: "trigger a build of wheels"
    python: 3.7
    script: if [[ ($TRAVIS_BRANCH = "master" || $TRAVIS_BRANCH =~ testing-*) && $TRAVIS_PULL_REQUEST = "false" ]]; then ./misc/trigger_wheel_build.sh; fi
  - name: "check dev environment builds"
    python: 3.7
    env:
    - TOXENV=dev
    - EXTRA_ARGS=

install:
- pip install -U pip setuptools
- pip install -U tox
- tox --notest

script:
- tox -- $EXTRA_ARGS
